//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Applications.Utilities.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Applications.Utilities.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smestaj:.
        /// </summary>
        public static string Accommodation_ {
            get {
                return ResourceManager.GetString("Accommodation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o smestaju.
        /// </summary>
        public static string Accommodation_info {
            get {
                return ResourceManager.GetString("Accommodation info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o nalogu.
        /// </summary>
        public static string Account_info {
            get {
                return ResourceManager.GetString("Account info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Sliku.
        /// </summary>
        public static string Add_Image {
            get {
                return ResourceManager.GetString("Add Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve Rezervacije.
        /// </summary>
        public static string All_Reservations {
            get {
                return ResourceManager.GetString("All Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartman.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odobri.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecna ocena:.
        /// </summary>
        public static string Average_grade_ {
            get {
                return ResourceManager.GetString("Average grade:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zauzetost.
        /// </summary>
        public static string Busyness {
            get {
                return ResourceManager.GetString("Busyness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazi.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dani za otkazivanje pre rezervacije.
        /// </summary>
        public static string Cancel_days_before_reservation {
            get {
                return ResourceManager.GetString("Cancel days before reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dani za otkazivanje pre rezervacije:.
        /// </summary>
        public static string Cancel_days_before_reservation_ {
            get {
                return ResourceManager.GetString("Cancel days before reservation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazivanja.
        /// </summary>
        public static string Cancelations {
            get {
                return ResourceManager.GetString("Cancelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacitet:.
        /// </summary>
        public static string Capacity_ {
            get {
                return ResourceManager.GetString("Capacity:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni jezik:.
        /// </summary>
        public static string Change_Language_ {
            get {
                return ResourceManager.GetString("Change Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni temu:.
        /// </summary>
        public static string Change_theme_ {
            get {
                return ResourceManager.GetString("Change theme:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad:.
        /// </summary>
        public static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad i Drzava:.
        /// </summary>
        public static string City_and_Country_ {
            get {
                return ResourceManager.GetString("City and Country:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cistoca.
        /// </summary>
        public static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar:.
        /// </summary>
        public static string Comment_ {
            get {
                return ResourceManager.GetString("Comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentari:.
        /// </summary>
        public static string Comments_ {
            get {
                return ResourceManager.GetString("Comments:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koliba.
        /// </summary>
        public static string Cottage {
            get {
                return ResourceManager.GetString("Cottage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava:.
        /// </summary>
        public static string Country_ {
            get {
                return ResourceManager.GetString("Country:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna tema.
        /// </summary>
        public static string Dark_Theme {
            get {
                return ResourceManager.GetString("Dark Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do: .
        /// </summary>
        public static string End_date_ {
            get {
                return ResourceManager.GetString("End date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procena trajanja:.
        /// </summary>
        public static string Estimated_length_ {
            get {
                return ResourceManager.GetString("Estimated length:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadji termine.
        /// </summary>
        public static string Find_terms {
            get {
                return ResourceManager.GetString("Find terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forumi.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idi nazad.
        /// </summary>
        public static string Go_Back {
            get {
                return ResourceManager.GetString("Go Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuca.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostavi komentar.
        /// </summary>
        public static string Leave_a_comment {
            get {
                return ResourceManager.GetString("Leave a comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla tema.
        /// </summary>
        public static string Light_Theme {
            get {
                return ResourceManager.GetString("Light Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        public static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izloguj se.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj gostiju.
        /// </summary>
        public static string Maximum_number_of_guests {
            get {
                return ResourceManager.GetString("Maximum number of guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalano dana rezervacije.
        /// </summary>
        public static string Minimum_days_of_reservation {
            get {
                return ResourceManager.GetString("Minimum days of reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno dana rezervacije:.
        /// </summary>
        public static string Minimum_number_of_days_ {
            get {
                return ResourceManager.GetString("Minimum number of days:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razno / dodaj Slike.
        /// </summary>
        public static string Miscellaneous___add_Images {
            get {
                return ResourceManager.GetString("Miscellaneous / add Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeranje Rezervacija.
        /// </summary>
        public static string Move_Requests {
            get {
                return ResourceManager.GetString("Move Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moji smestaji.
        /// </summary>
        public static string My_accommodations {
            get {
                return ResourceManager.GetString("My accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv i Lokacija.
        /// </summary>
        public static string Name_and_Location {
            get {
                return ResourceManager.GetString("Name and Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sledeca.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavestenja.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prijava:.
        /// </summary>
        public static string Number_of_reports_ {
            get {
                return ResourceManager.GetString("Number of reports:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavite komentar.
        /// </summary>
        public static string Post_the_Comment {
            get {
                return ResourceManager.GetString("Post the Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istampaj.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni Gosta.
        /// </summary>
        public static string Rate_the_Guest {
            get {
                return ResourceManager.GetString("Rate the Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj Smestaj.
        /// </summary>
        public static string Register_Accommodation {
            get {
                return ResourceManager.GetString("Register Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija (1/3).
        /// </summary>
        public static string Registration__1_3_ {
            get {
                return ResourceManager.GetString("Registration (1/3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija (2/3).
        /// </summary>
        public static string Registration__2_3_ {
            get {
                return ResourceManager.GetString("Registration (2/3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija (3/3).
        /// </summary>
        public static string Registration__3_3_ {
            get {
                return ResourceManager.GetString("Registration (3/3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviraj.
        /// </summary>
        public static string Renovate {
            get {
                return ResourceManager.GetString("Renovate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preporuke Renoviranja.
        /// </summary>
        public static string Renovation_Recommendations {
            get {
                return ResourceManager.GetString("Renovation Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovacije.
        /// </summary>
        public static string Renovations {
            get {
                return ResourceManager.GetString("Renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeranja.
        /// </summary>
        public static string Reschedulings {
            get {
                return ResourceManager.GetString("Reschedulings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacije.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje Rezervacijama.
        /// </summary>
        public static string Reservations_Management {
            get {
                return ResourceManager.GetString("Reservations Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji recenzije.
        /// </summary>
        public static string Review_Details {
            get {
                return ResourceManager.GetString("Review Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzije.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postovanje pravila.
        /// </summary>
        public static string Rule_respect {
            get {
                return ResourceManager.GetString("Rule respect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi:.
        /// </summary>
        public static string Select_ {
            get {
                return ResourceManager.GetString("Select:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podesavanja.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od: .
        /// </summary>
        public static string Start_date_ {
            get {
                return ResourceManager.GetString("Start date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najzauzetije vreme:.
        /// </summary>
        public static string The_most_occupied_time_ {
            get {
                return ResourceManager.GetString("The most occupied time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •Proputujte Svet•.
        /// </summary>
        public static string Travel_the_World {
            get {
                return ResourceManager.GetString("Travel the World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        public static string Type_ {
            get {
                return ResourceManager.GetString("Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbij.
        /// </summary>
        public static string Unapprove {
            get {
                return ResourceManager.GetString("Unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neocenjeni Gosti.
        /// </summary>
        public static string Unrated_Guests {
            get {
                return ResourceManager.GetString("Unrated Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sliku.
        /// </summary>
        public static string Upload_Picture {
            get {
                return ResourceManager.GetString("Upload Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime:.
        /// </summary>
        public static string Username_ {
            get {
                return ResourceManager.GetString("Username:", resourceCulture);
            }
        }
    }
}
